### ISSUE TITLE
Network disconnect results in unhandled promise rejection, causing nodecg to exit

### ISSUE THREAD

**Issue by jai-x** [daniellockard/nodecg-tiltify#6]
When using the `nodecg-tiltify` bundle, I have found that when this bundle is correctly configured and running on a `nodecg` server, if the server is to lose network connection, the next API request made to Tiltify results in an unhandled promise rejection which ends up causing the `nodecg` server to exit.

Ideally this bundle should be able to gracefully handle network outages and not cause the entire server to crash.

Steps for reproduction:
* Install `nodecg` and `nodecg-tiltify` on local computer
* Confgure `nodecg-tiltify` with a Tiltify API key and Campaign id
* Start `nodecg` and verify that `nodecg-tiltfy` is correctly pulling information from Tiltify
* Disconnect computer from network (in my case turn off laptop wifi)

System info:
* `node` version: `13.7.0`
* `nodecg` version: `1.5.0`
* `nodecg-tiltify` version: 1a0efcfcda1f4bd14ef442cdc45d9a09aeeef050

Crash log with API token censored:
```js
RequestError: Error: getaddrinfo ENOTFOUND tiltify.com
    at new RequestError (/Users/jai.sharma/src/github.com/jai-x/nodecg/bundles/nodecg-tiltify/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/jai.sharma/src/github.com/jai-x/nodecg/bundles/nodecg-tiltify/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/jai.sharma/src/github.com/jai-x/nodecg/bundles/nodecg-tiltify/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/jai.sharma/src/github.com/jai-x/nodecg/bundles/nodecg-tiltify/node_modules/request/request.js:185:22)
    at Request.emit (events.js:321:20)
    at Request.EventEmitter.emit (domain.js:485:12)
    at Request.onRequestError (/Users/jai.sharma/src/github.com/jai-x/nodecg/bundles/nodecg-tiltify/node_modules/request/request.js:881:8)
    at ClientRequest.emit (events.js:321:20)
    at ClientRequest.EventEmitter.emit (domain.js:485:12)
    at TLSSocket.socketErrorListener (_http_client.js:424:9)
    at TLSSocket.emit (events.js:321:20)
    at TLSSocket.EventEmitter.emit (domain.js:485:12)
    at emitErrorNT (internal/streams/destroy.js:84:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  name: 'RequestError',
  message: 'Error: getaddrinfo ENOTFOUND tiltify.com',
  cause: Error: getaddrinfo ENOTFOUND tiltify.com
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:64:26) {
    errno: -3008,
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'tiltify.com'
  },
  error: Error: getaddrinfo ENOTFOUND tiltify.com
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:64:26) {
    errno: -3008,
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'tiltify.com'
  },
  options: {
    url: 'https://tiltify.com/api/v3/campaigns/41257/donations',
    headers: {
      Authorization: 'Bearer CENSORED_API_TOKEN'
    },
    callback: [Function: RP$callback],
    transform: undefined,
    simple: true,
    resolveWithFullResponse: false,
    transform2xxOnly: false
  },
  response: undefined
}
UNCAUGHT EXCEPTION! NodeCG will now exit.
abort({"name":"RequestError","message":"Error: getaddrinfo ENOTFOUND tiltify.com","cause":{"errno":-3008,"code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"tiltify.com"},"error":{"errno":-3008,"code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"tiltify.com"},"options":{"url":"https://tiltify.com/api/v3/campaigns/41257/donations","headers":{"Authorization":"Bearer CENSORED_API_TOKEN,"simple":true,"resolveWithFullResponse":false,"transform2xxOnly":false}}). Build with -s ASSERTIONS=1 for more info.
```

**Comment by daniellockard** [comment]
@jai-x I apologize for just now seeing this. I'll take a look and see if I need to be catching some errors. I've seen this happen myself, but I use `pm2` to manage the processes and it normally restarts fine.

**Comment by daniellockard** [comment]
I believe this is fixed here: https://github.com/daniellockard/tiltify-api-client/tree/v1.1.1

1.1.1 is publishing to NPM now.
